"""Markdown report generator for GEO analysis results."""
from datetime import datetime


def generate_markdown_report(data: dict) -> str:
    """Generate a structured markdown report from analysis results."""
    url = data.get("url", "")
    brand_name = data.get("brand_name", url.split("/")[2] if "/" in url else url)
    date = data.get("date", datetime.now().strftime("%Y-%m-%d"))
    geo_score = data.get("geo_score", 0)
    scores = data.get("scores", {})
    platforms = data.get("platforms", {})
    findings = data.get("findings", [])
    action_plan = data.get("action_plan", {})
    crawler_access = data.get("crawler_access", {})

    grade = data.get("grade", "")
    label = data.get("label", "")

    lines = []
    lines.append(f"# GEO Analysis Report: {brand_name}")
    lines.append(f"")
    lines.append(f"**URL:** {url}  ")
    lines.append(f"**Date:** {date}  ")
    lines.append(f"**GEO Score:** {geo_score}/100 — {label}  ")
    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")

    # Score Breakdown
    lines.append(f"## Score Breakdown")
    lines.append(f"")
    lines.append(f"| Category | Score | Weight | Weighted |")
    lines.append(f"|----------|-------|--------|----------|")

    weights = {"ai_citability": 0.25, "brand_authority": 0.20, "content_eeat": 0.20,
               "technical": 0.15, "schema": 0.10, "platform_optimization": 0.10}
    labels = {"ai_citability": "AI Citability & Visibility", "brand_authority": "Brand Authority Signals",
              "content_eeat": "Content Quality & E-E-A-T", "technical": "Technical Foundations",
              "schema": "Structured Data", "platform_optimization": "Platform Optimization"}

    for cat, weight in weights.items():
        s = scores.get(cat, 0)
        lines.append(f"| {labels.get(cat, cat)} | {s}/100 | {int(weight*100)}% | {round(s*weight, 1)} |")
    lines.append(f"| **OVERALL** | **{geo_score}/100** | **100%** | **{geo_score}** |")
    lines.append(f"")

    # Platform Readiness
    if platforms:
        lines.append(f"## AI Platform Readiness")
        lines.append(f"")
        lines.append(f"| Platform | Score | Status |")
        lines.append(f"|----------|-------|--------|")
        for name, score in platforms.items():
            status = "Excellent" if score >= 80 else "Good" if score >= 60 else "Moderate" if score >= 40 else "Needs Work"
            lines.append(f"| {name} | {score}/100 | {status} |")
        lines.append(f"")

    # AI Crawler Access
    if crawler_access:
        lines.append(f"## AI Crawler Access")
        lines.append(f"")
        lines.append(f"| Crawler | Status |")
        lines.append(f"|---------|--------|")
        for crawler, status in crawler_access.items():
            emoji = "ALLOWED" if "ALLOW" in str(status) else "BLOCKED" if "BLOCK" in str(status) else str(status)
            lines.append(f"| {crawler} | {emoji} |")
        lines.append(f"")

    # Key Findings
    if findings:
        lines.append(f"## Key Findings")
        lines.append(f"")
        for finding in findings:
            severity = finding.get("severity", "info").upper()
            title = finding.get("title", "")
            desc = finding.get("description", "")
            lines.append(f"**[{severity}] {title}**  ")
            if desc:
                lines.append(f"{desc}")
            lines.append(f"")

    # Action Plan
    if action_plan:
        lines.append(f"## Prioritized Action Plan")
        lines.append(f"")

        quick_wins = action_plan.get("quick_wins", [])
        if quick_wins:
            lines.append(f"### Quick Wins (This Week)")
            for i, item in enumerate(quick_wins, 1):
                action = item.get("action", item) if isinstance(item, dict) else item
                lines.append(f"{i}. {action}")
            lines.append(f"")

        medium_term = action_plan.get("medium_term", [])
        if medium_term:
            lines.append(f"### Medium-Term (This Month)")
            for i, item in enumerate(medium_term, 1):
                action = item.get("action", item) if isinstance(item, dict) else item
                lines.append(f"{i}. {action}")
            lines.append(f"")

        strategic = action_plan.get("strategic", [])
        if strategic:
            lines.append(f"### Strategic (This Quarter)")
            for i, item in enumerate(strategic, 1):
                action = item.get("action", item) if isinstance(item, dict) else item
                lines.append(f"{i}. {action}")
            lines.append(f"")

    lines.append(f"---")
    lines.append(f"*Generated by GEO Analyzer on {date}*")

    return "\n".join(lines)
